spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 # 2 HR
    accessRefreshExpiration: 604800 # 7days

server:
  port: 8081